Specialization 3
szwajkowska/medicare pull request #1
Opened 2017-07-16 20:01 UTC by szwajkowska

2017-07-16 20:39 UTC, szwajkowski requested changes

2017-07-16 20:39 UTC, szwajkowski commented on build.gradle
> +//    compile group: 'org.mongodb', name: 'mongo-java-driver', version: '3.4.2'
nie potrzebujemy zakomentowanego kodu

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/Application.java
> +
warto sformatować kod

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/AdminController.java
> +public class AdminController {
public nie jest potrzebne

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/AdminDoctorController.java
> +    public AdminDoctorController(DoctorService doctorService, SpecializationList specializationList) {
public do usuniecia

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/AdminDoctorController.java
> +    String showAdminDoctorPage(ModelMap model, DoctorModel doctorModel) {
doctorModel jest nieuzywany

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/AdminDoctorController.java
> +    String deleteDoctor(@PathVariable String id, ModelMap model, DoctorModel doctorModel) {
sprawdzić czy doctorModel jest potrzebny

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/AdminSpecializationController.java
> +//    String showSpecialization(@PathVariable String specializationName){
do wywalenia

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/DoctorModel.java
> +    private String lastName;
pola przed metodami

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/DoctorsController.java
> +        return specializationList.findById(specializationId).getDoctors()
ta logika powinna być w serwisie

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/domain/SpecializationList.java
> +    public List<Specialization> showAllSpecializations(){
może lepiej nazwać tę metodę `findAll`

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/domain/doctors/Doctor.java
> +    @Cascade(org.hibernate.annotations.CascadeType.DELETE)
import

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/domain/doctors/DoctorService.java
> +        return StreamSupport.stream(doctorRepository.findAll().spliterator(), false)
można wywalic spliterator i zrobić `findAll().stream()`

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/domain/doctors/DoctorService.java
> +        specializations.add(specializationList.findById(specializationId));
zamiast
```
List<Specialization> specializations = new ArrayList<>();
specializations.add(specializationList.findById(specializationId));
```

można napisać
```
List<Specialization> specializations = Arrays.asList(specializationList.findById(specializationId));
```

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/domain/doctors/DoctorService.java
> +        specializations.add(specializationList.findById(specializationId));
pierdoła

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/security/User.java
> +    @javax.persistence.Id
import

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/security/UserList.java
> +    public Iterable<User> showAllUsers(){
nieużywane

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/security/UserModel.java
> +    @Length(min = 3, message = "length must have 3 or more chars")
message można dać do stałej bo sie 3x powtarza

2017-07-16 20:39 UTC, szwajkowski commented on src/main/java/pl/ania/security/UserModel.java
> +    private String email;
sprawdz czy jest walidator do maila

2017-07-16 20:39 UTC, szwajkowski commented on src/main/resources/static/delete.js
> +    req.open('DELETE', '/admin/specialization/' + id, true);
tu jest do dodania listener onreadystatechange

2017-07-16 20:39 UTC, szwajkowski commented on src/main/resources/templates/admin_specialization.html
> +    <li th:each="prod : ${specializations}">
nazwa prod do zmiany

2017-07-16 20:39 UTC, szwajkowski commented on src/main/resources/templates/admin_specialization.html
> +            <label for ="id"><span th:text="${prod.specializationName}"></span><span th:text="${prod.id}"></span></label>
prod.id mozna nie wyświetlać

2017-07-21 12:11 UTC, szwajkowska commented on src/main/java/pl/ania/security/UserModel.java
> +    @Length(min = 3, message = "length must have 3 or more chars")
nie umiem

2017-07-21 12:13 UTC, szwajkowski commented on src/main/java/pl/ania/security/UserModel.java
> +    @Length(min = 3, message = "length must have 3 or more chars")
private static final String  MESSAGE = "length must have 3 or more chars";

2017-07-21 12:13 UTC, szwajkowska commented on src/main/java/pl/ania/security/UserModel.java
> +    private String email;
nie wiem o co chodzi

2017-07-21 12:14 UTC, szwajkowski commented on src/main/java/pl/ania/security/UserModel.java
> +    private String email;
@Email - taka adnotacja

2017-07-21 12:18 UTC, szwajkowska commented on src/main/java/pl/ania/security/UserModel.java
> +    private String email;
ale po co?

2017-07-21 12:19 UTC, szwajkowski commented on src/main/java/pl/ania/security/UserModel.java
> +    private String email;
a po co Ci walidacja na password?

2017-07-25 19:08 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/LoginController.java
> +
duuuzo wolnych linii

2017-07-25 19:08 UTC, szwajkowski commented on src/main/java/pl/ania/domain/doctors/Doctor.java
> +import org.hibernate.annotations.*;
* w importach

2017-07-25 19:08 UTC, szwajkowski commented on src/main/resources/static/delete.js
> +    req.open('DELETE', '/admin/doctor/' + id, false);
false -> true

2017-07-25 19:08 UTC, szwajkowski commented on src/main/resources/static/delete.js
> +            console.log(req.responseText);
console.log jest nie potrzebny

2017-07-25 19:08 UTC, szwajkowski commented on src/main/resources/templates/admin_doctor.html
> +    <option th:each="prod : ${specializations}"
prod do zmiany

2017-07-25 19:08 UTC, szwajkowski commented on src/main/resources/templates/admin_specialization.html
> +    <!--<li th:each="prod : ${notes}">-->
zakomentowany kod do wywalenia

2017-07-25 19:08 UTC, szwajkowski commented on src/main/resources/templates/signIn.html
> +            <!--<td><input type="text" name="username"></td>-->
komentarze do wywalenia

2017-07-25 19:08 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/AdminDoctorController.java
> +        return "admin_doctor"; //zmieniłam na admin-doctor, usunęłam doctorModel
tu mozna zwracać void zamiast Stringa i htmla

2017-07-25 19:08 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/AdminDoctorController.java
> +import org.springframework.web.bind.annotation.*;
*

2017-07-25 19:40 UTC, szwajkowski approved these changes

2017-07-25 19:41 UTC, merged