Date
szwajkowska/medicare pull request #2
Opened 2017-08-21 19:38 UTC by szwajkowska

2017-08-22 17:27 UTC, szwajkowski commented on src/main/java/pl/ania/Application.java
> +import com.fasterxml.jackson.databind.ObjectMapper;
notused

2017-08-22 17:38 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/AdminVisitController.java
> +//                return "redirect:/admin/visit?doctorId_error";
komentarz

2017-08-22 17:38 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/VisitsController.java
> +    @ResponseBody//response bo zwraca odpowiedź
jak jest @RestController to nie trzeba dawać @ResponseBody

2017-08-22 17:38 UTC, szwajkowski commented on src/main/java/pl/ania/domain/doctors/Doctor.java
> +import javax.persistence.*;
gwiazdka

2017-08-22 17:38 UTC, szwajkowski commented on src/main/java/pl/ania/domain/visits/Visit.java
> +        this.id = id;
lepiej by było gdyby ten konstruktor używał tego drugiego czyli:
```
this(id, dateOfVisit,...)
```

2017-08-22 17:38 UTC, szwajkowski commented on src/main/java/pl/ania/domain/visits/Visit.java
> +    private Date dateOfVisit;
ta nazwa jest bez sensu skoro to jest w klasie Visit

2017-08-22 17:38 UTC, szwajkowski commented on src/main/java/pl/ania/domain/visits/VisitService.java
> +        return Optional.ofNullable(visitRepository.findByDateOfVisitAndDoctorId(dateOfVisit, doctorId));
można zmienić zwracany typ na Optional<Visit> w metodzie findByDateOfVisitAndDoctorId i nie bawić sie w owijanie

2017-08-22 17:38 UTC, szwajkowski commented on src/main/java/pl/ania/domain/visits/Visit.java
> +    private boolean taken;
to pole jest już bez sensu skoro jest ustawione na true tylko jak jest user != null

2017-08-22 17:38 UTC, szwajkowski commented on src/main/java/pl/ania/domain/visits/VisitService.java
> +        visitRepository.save(new Visit(id, visitById.getDateOfVisit(), visitById.getDoctor(), true, user.get(), visitById.getSpecialization()));
przydałby sie builder, bo to jest mało czytelne

2017-08-22 17:38 UTC, szwajkowski commented on src/main/java/pl/ania/security/WebSecurityConfig.java
> +//        auth. inMemoryAuthentication()
komentarz

2017-08-22 17:38 UTC, szwajkowski commented on src/main/java/pl/ania/domain/doctors/DoctorRepository.java
> +    Doctor findByVisits(List<Visit> visits);
nie jest nigdzie używane

2017-08-23 13:04 UTC, szwajkowska commented on src/main/java/pl/ania/domain/visits/Visit.java
> +        this.id = id;
Nie rozumiem

2017-08-23 13:07 UTC, szwajkowska commented on src/main/java/pl/ania/domain/visits/VisitService.java
> +        visitRepository.save(new Visit(id, visitById.getDateOfVisit(), visitById.getDoctor(), true, user.get(), visitById.getSpecialization()));
co to builder?

2017-09-02 19:56 UTC, szwajkowski requested changes

2017-09-02 19:56 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/VisitResponse.java
> +    private final Date dateOfVisit;
tu jeszcze date

2017-09-02 19:56 UTC, szwajkowski commented on src/main/java/pl/ania/controllers/VisitModel.java
> +    private Date dateOfVisit;
date

2017-09-04 09:09 UTC, merged